### PR TITLE
Refactor main robot class to use CommandRobot

### PR DESCRIPTION
**Pull request by spacey-sooty**

### CODE REVIEW

**Comment by Hazzer890** [comment]
1) Has this been tested on a robot? I presume not. 2) How confident are you the changes will work? And how prepared are you to revert from refactor

**Comment by spacey-sooty** [comment]
> 1. Has this been tested on a robot? I presume not. 2) How confident are you the changes will work? And how prepared are you to revert from refactor

1. hasn't been
2. very confident but if I need to revert I will

**Review by Hazzer890 — APPROVED** [review]
Sounds good, lets switch back if its not working when robot is ready to test

**Comment by spacey-sooty** [comment]
I'll have a play around in sim and try and break it b4 merging

**Pull request merged**
